---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: cluster-config
spec:
  targetNamespace: ingress-nginx
  releaseName: ingress-nginx
  chart:
    spec:
      chart: nginx-ingress-controller
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: cluster-config
      version: "1.11.0"
  interval: 10m0s
  install:
    remediation:
      retries: 3
  values:
    service:
      type: LoadBalancer
    ingressClassResource:
      name: nginx
    resourcesPreset: small
    metadata:
      labels:
        app: nginx
