apiVersion: apps/v1
kind: Deployment
metadata:
  name: store-firewall
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cfos
  template:
    metadata:
      labels:
        app: cfos
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: cfos
        image: frobozzcanadacentralacr.azurecr.io/cfos:latest
        ports:
        - containerPort: 80
          name: cfos
        volumeMounts:
        - mountPath: /data
          name: data-volume
        env:
        - name: cfos-license
          valueFrom:
            configMapKeyRef:
              name: cfos-license
              key: license
        securityContext:
          capabilities:
              add: ["NET_ADMIN","SYS_ADMIN","NET_RAW"]
        resources:
          requests:
            cpu: 1m
            memory: 200Mi
          limits:
            cpu: 1000m
            memory: 512Mi
      volumes:
      - name: data-volume
        hostPath:
          path: /cfosdata
          type: DirectoryOrCreate
