---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
    name: config-map-manager
rules:
    - apiGroups: [""]
      resources: ["configmaps"]
      verbs: ["create", "get", "list", "watch", "update", "delete", "patch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
    name: config-map-manager
    namespace: fos
subjects:
    - kind: ServiceAccount
      name: default
      apiGroup: ""
      namespace: dvwa
roleRef:
    kind: ClusterRole
    name: config-map-manager
    apiGroup: ""

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
    name: dvwa-svc-reader
rules:
    - apiGroups: [""]
      resources: ["services"]
      verbs: ["get", "watch", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
    name: dvwa-read-svc
    namespace: dvwa
subjects:
    - kind: ServiceAccount
      name: default
      apiGroup: ""
      namespace: dvwa
roleRef:
    kind: ClusterRole
    name: dvwa-svc-reader
    apiGroup: ""
