---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
    name: dvwa-svc-reader
rules:
    - apiGroups: [""]
      resources: ["services"]
      verbs: ["get", "watch", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
    name: dvwa-read-svc
    namespace: dvwa
subjects:
    - kind: ServiceAccount
      name: default
      apiGroup: ""
      namespace: fos
roleRef:
    kind: ClusterRole
    name: dvwa-svc-reader
    apiGroup: ""
