apiVersion: v1
data:
  config: |-
    config firewall vip
        edit "dvwa-vip"
            set extip "fostest-headless"
            set mappedip dvwa.dvwa.svc.cluster.local
            set extintf "eth0"
            set portforward enable
            set extport "8001"
            set mappedport "80"
        next
    end
    config firewall policy
        edit 1
            set name "dvwa"
            set srcintf "eth0"
            set dstintf "eth0"
            set srcaddr "all"
            set dstaddr "dvwa-vip"
            set service "ALL"
            set nat enable
            set action accept
        next
    end
  type: partial
kind: ConfigMap
metadata:
  creationTimestamp: "2024-06-27T17:02:27Z"
  labels:
    app: fos
    category: config
    kustomize.toolkit.fluxcd.io/name: ingress-fos-infrastructure
    kustomize.toolkit.fluxcd.io/namespace: cluster-config
  name: fosconfigvip
  namespace: fos
  resourceVersion: "78020"
  uid: 497dc71c-b5a2-4a72-a605-f2ecf8e5ba88
