apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2024-07-02T13:53:46Z"
  generateName: dvwa-687b979b48-
  labels:
    app: dvwa
    pod-template-hash: 687b979b48
  name: dvwa-687b979b48-j5s62
  namespace: dvwa
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: dvwa-687b979b48
    uid: 59931df0-e97b-4c61-a85a-cb4502b6e0e6
  resourceVersion: "15717"
  uid: 9beeec64-1263-41f1-9f89-d1cb9c9f469d
spec:
  containers:
  - env:
    - name: DB_SERVER
      value: mariadb
    image: ghcr.io/digininja/dvwa:latest
    imagePullPolicy: Always
    name: dvwa
    ports:
    - containerPort: 80
      name: http
      protocol: TCP
    resources:
      limits:
        cpu: "1"
        memory: 512Mi
      requests:
        cpu: 1m
        memory: 200Mi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-nw79n
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  initContainers:
  - command:
    - sh
    - --c
    - kubectl -n dvwa get svc dvwa -o json
    image: alpine/k8s:1.30.2
    imagePullPolicy: IfNotPresent
    name: init-myservice
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-nw79n
      readOnly: true
  nodeName: aks-default-18604477-vmss000000
  nodeSelector:
    kubernetes.io/os: linux
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  - effect: NoSchedule
    key: node.kubernetes.io/memory-pressure
    operator: Exists
  volumes:
  - name: kube-api-access-nw79n
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2024-07-02T13:53:48Z"
    status: "True"
    type: PodReadyToStartContainers
  - lastProbeTime: null
    lastTransitionTime: "2024-07-02T13:53:46Z"
    message: 'containers with incomplete status: [init-myservice]'
    reason: ContainersNotInitialized
    status: "False"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2024-07-02T13:53:46Z"
    message: 'containers with unready status: [dvwa]'
    reason: ContainersNotReady
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2024-07-02T13:53:46Z"
    message: 'containers with unready status: [dvwa]'
    reason: ContainersNotReady
    status: "False"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2024-07-02T13:53:46Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - image: ghcr.io/digininja/dvwa:latest
    imageID: ""
    lastState: {}
    name: dvwa
    ready: false
    restartCount: 0
    started: false
    state:
      waiting:
        reason: PodInitializing
  hostIP: 10.224.0.4
  hostIPs:
  - ip: 10.224.0.4
  initContainerStatuses:
  - containerID: containerd://4171b6202a9e959eb1f212b027ddba130b9d0d2b6bc43c69bacf97562e85c502
    image: docker.io/alpine/k8s:1.30.2
    imageID: docker.io/alpine/k8s@sha256:cd560fce90f76d2da46bce0624b65258c45ab3350f7073d6722fa74c7b3a3601
    lastState:
      terminated:
        containerID: containerd://4171b6202a9e959eb1f212b027ddba130b9d0d2b6bc43c69bacf97562e85c502
        exitCode: 2
        finishedAt: "2024-07-02T13:53:48Z"
        reason: Error
        startedAt: "2024-07-02T13:53:48Z"
    name: init-myservice
    ready: false
    restartCount: 1
    started: false
    state:
      waiting:
        message: back-off 10s restarting failed container=init-myservice pod=dvwa-687b979b48-j5s62_dvwa(9beeec64-1263-41f1-9f89-d1cb9c9f469d)
        reason: CrashLoopBackOff
  phase: Pending
  podIP: 10.224.0.10
  podIPs:
  - ip: 10.224.0.10
  qosClass: Burstable
  startTime: "2024-07-02T13:53:46Z"
