apiVersion: v1
kind: Pod
metadata:
  annotations:
    container.apparmor.security.beta.kubernetes.io/fos: unconfined
  creationTimestamp: "2024-06-29T01:17:34Z"
  generateName: fos-8fcb5d4b6-
  labels:
    api: allow
    app: fos
    pod-template-hash: 8fcb5d4b6
  name: fos-8fcb5d4b6-dk7c8
  namespace: fos
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: fos-8fcb5d4b6
    uid: 0ecc7dfc-4b8f-449a-8202-3930ff716ed7
  resourceVersion: "5503"
  uid: e18fb492-07a6-4c57-83c1-e74fef392188
spec:
  containers:
  - env:
    - name: fos-license
      valueFrom:
        configMapKeyRef:
          key: license
          name: fos-license
    image: ghcr.io/robinmordasiewicz/fos:latest
    imagePullPolicy: Always
    name: fos
    ports:
    - containerPort: 80
      name: fos
      protocol: TCP
    - containerPort: 500
      name: isakmp
      protocol: UDP
    - containerPort: 4500
      name: ipsec-nat-t
      protocol: UDP
    resources:
      limits:
        cpu: "8"
        memory: 4Gi
      requests:
        cpu: 4m
        memory: 2Gi
    securityContext:
      allowPrivilegeEscalation: true
      capabilities:
        add:
        - NET_ADMIN
        - SYS_ADMIN
        - NET_RAW
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /data
      name: data-volume
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-kr2fq
      readOnly: true
  - command:
    - sleep
    - "604800"
    image: ghcr.io/robinmordasiewicz/devcontainer@sha256:01962cc8185dea71c4d46151542c56b00ef45c6f198a54e772a35249fa6ed97c
    imagePullPolicy: IfNotPresent
    name: devcontainer
    resources:
      limits:
        cpu: "1"
        memory: 512Mi
      requests:
        cpu: 1m
        memory: 200Mi
    securityContext:
      allowPrivilegeEscalation: true
      runAsGroup: 1000
      runAsUser: 1000
    stdin: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    tty: true
    volumeMounts:
    - mountPath: /data
      name: data-volume
    - mountPath: /opt/bin
      name: sidecar-volume
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-kr2fq
      readOnly: true
    workingDir: /home/vscode
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: aks-default-38696457-vmss000001
  nodeSelector:
    kubernetes.io/os: linux
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  - effect: NoSchedule
    key: node.kubernetes.io/memory-pressure
    operator: Exists
  volumes:
  - emptyDir: {}
    name: data-volume
  - configMap:
      defaultMode: 493
      name: sidecar
    name: sidecar-volume
  - name: kube-api-access-kr2fq
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2024-06-29T01:19:47Z"
    status: "True"
    type: PodReadyToStartContainers
  - lastProbeTime: null
    lastTransitionTime: "2024-06-29T01:17:34Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2024-06-29T01:19:47Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2024-06-29T01:19:47Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2024-06-29T01:17:34Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://af6e80b2e27b3273475cf2151ab8e75b3c7bfbb3bef0e3ba01744e7bf3b73617
    image: sha256:63301003aa1872feb815a3a3df6471881e1b4f49b2fb0aced03129f095dc8ddf
    imageID: ghcr.io/robinmordasiewicz/devcontainer@sha256:01962cc8185dea71c4d46151542c56b00ef45c6f198a54e772a35249fa6ed97c
    lastState: {}
    name: devcontainer
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2024-06-29T01:19:47Z"
  - containerID: containerd://fa9270053b39743e0a4f708d2423987fc628ada8a16075753883f8f06dbe245f
    image: ghcr.io/robinmordasiewicz/fos:latest
    imageID: ghcr.io/robinmordasiewicz/fos@sha256:6f55405522c85bbcf01c999d33d5ef954f66d7aed1c1590117b4f6263cf45c2b
    lastState: {}
    name: fos
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2024-06-29T01:17:37Z"
  hostIP: 10.224.0.4
  hostIPs:
  - ip: 10.224.0.4
  phase: Running
  podIP: 10.224.0.8
  podIPs:
  - ip: 10.224.0.8
  qosClass: Burstable
  startTime: "2024-06-29T01:17:34Z"
