---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ollama
  namespace: cluster-config
spec:
  targetNamespace: ollama
  releaseName: ollama
  chart:
    spec:
      chart: ollama
      sourceRef:
        kind: HelmRepository
        name: ollama
        namespace: cluster-config
      version: "0.x"
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
