---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: fortiweb-ingress-controller
  namespace: cluster-config
spec:
  targetNamespace: fortiweb-ingress-controller
  releaseName: fortiweb-ingress-controller
  chart:
    spec:
      chart: fortiweb-ingress-controller
      sourceRef:
        kind: HelmRepository
        name: fortiweb-ingress-controller
        namespace: cluster-config
      version: "1.0.2"
  interval: 10m0s
  install:
    remediation:
      retries: 3
