---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: infrastructure
  namespace: cluster-config
spec:
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: cluster-config
  path: ./infrastructure
  prune: true
