---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-devcontainer-default-ns
  namespace: fos
spec:
  egress:
  - to:
    - ipBlock:
        cidr: 10.0.0.1/32
    ports:
    - protocol: TCP
      port: 443
  podSelector:
    matchLabels:
      app: devcontainer
  - to:
    - ipBlock:
        cidr: 10.0.0.10/32
    ports:
    - protocol: UDP
      port: 53
  podSelector:
    matchLabels:
      app: devcontainer
  policyTypes:
  - Egress
