---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-all-dns-ns
  namespace: kube-system
spec:
  - podSelector:
      matchLabels:
        k8s-app: kube-dns
  policyTypes:
    - Ingress
  ingress:
  - from:
    - ipBlock:
        cidr: 10.0.0.10/32
    - namespaceSelector: {}
    ports:
    - protocol: UDP
      port: 53
