---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-fos-default-ns
  namespace: fos
spec:
  egress:
  - to:
    - ipBlock:
        cidr: 0.0.0.0/0
    ports:
    - protocol: TCP
      port: 443
  podSelector:
    matchLabels:
      app: devcontainer
  policyTypes:
  - Egress
