---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-fos-default-ns
  namespace: fos
spec:
  podSelector: {}
  policyTypes:
    - Egress
  egress:
    - to:
        - ipBlock:
            cidr: 10.0.0.0/24
          ports:
            - protocol: TCP
              port: 443
