---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-fos-api-ns
  namespace: fos
spec:
  podSelector: {}
  policyTypes:
    - Egress
  egress:
  - to:
    - ipBlock:
        cidr: 0.0.0.0/0
    ports:
    - protocol: TCP
      port: 443
