---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-all-dns-ns
  namespace: fos
spec:
  podSelector:
    matchLabels:
      app: devcontainer
  policyTypes:
    - Egress
  egress:
  - to:
    - ipBlock:
        cidr: 10.0.0.10/32
    ports:
    - protocol: UDP
      port: 53
