---
apiVersion: v1
kind: ServiceAccount
metadata:
    name: fos-serviceaccount
imagePullSecrets:
    - name: fosimagepullsecret

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
    name: configmap-reader
rules:
    - apiGroups: [""]
      resources: ["configmaps"]
      verbs: ["get", "watch", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
    name: read-configmaps
subjects:
    - kind: ServiceAccount
      name: default
      apiGroup: ""
roleRef:
    kind: ClusterRole
    name: configmap-reader
    apiGroup: ""

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
    name: secrets-reader
rules:
    - apiGroups: [""]
      resources: ["secrets"]
      verbs: ["get", "watch", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
    name: read-secrets
subjects:
    - kind: ServiceAccount
      name: default
      apiGroup: ""
roleRef:
    kind: ClusterRole
    name: secrets-reader
    apiGroup: ""
