---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: devcontainer
  namespace: fos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devcontainer
  template:
    metadata:
      labels:
        app: devcontainer
        api: allow
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
        - name: devcontainer
          securityContext:
            allowPrivilegeEscalation: true
            runAsUser: 1000
            runAsGroup: 1000
          command:
            - "sleep"
            - "604800"
          stdin: true
          tty: true
          image: ghcr.io/robinmordasiewicz/devcontainer@sha256:01962cc8185dea71c4d46151542c56b00ef45c6f198a54e772a35249fa6ed97c
          workingDir: /home/vscode
          resources:
            requests:
              cpu: 1m
              memory: 200Mi
            limits:
              cpu: 1000m
              memory: 512Mi
