---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: devcontainer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devcontainer
  template:
    metadata:
      labels:
        app: devcontainer
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
        - name: devcontainer
          command:
            - "sleep"
            - "604800"
          image: ghcr.io/robinmordasiewicz/devcontainer:latest
          resources:
            requests:
              cpu: 1m
              memory: 200Mi
            limits:
                cpu: 1000m
                memory: 512Mi
