---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ubuntu
  template:
    metadata:
      labels:
        app: ubuntu
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
        - name: ubuntu
          command:
            - "sleep"
            - "604800"
          image: ubuntu:22.04
          resources:
            requests:
              cpu: 1m
              memory: 200Mi
            limits:
                cpu: 1000m
                memory: 512Mi
