apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress-controller-default-backend
  namespace: nginx
spec:
  ingressClassName: nginx-internal
  rules:
  - host: ajlab-nginx.canadacentral.cloudapp.azure.com
    http:
      paths:
      - backend:
          service:
            name: nginx-ingress-controller-default-backend
            port:
              number: 80
        path: /
        pathType: Prefix
