---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ollama
  namespace: cluster-config
spec:
  targetNamespace: ollama
  releaseName: ollama
  chart:
    spec:
      chart: ollama
      sourceRef:
        kind: HelmRepository
        name: ollama
        namespace: cluster-config
      version: "0.x"
  interval: 10m0s
  install:
    timeout: 20m
    remediation:
      retries: 5
  upgrade:
    timeout: 20m
  values:
    runtimeClass: nvidia
    extraEnv:
      - name: OLLAMA_KEEP_ALIVE
        value: "-1"
    resources:
      limits:
        nvidia.com/gpu: "0"
      requests:
        nvidia.com/gpu: "0"
    image:
      tag: "latest"
    ollama:
      gpu:
        enabled: true
      models:
        - nomic-embed-text
        - codestral:latest
    ingress:
      enabled: true
      className: "fwb-ingress-controller"
      #className: "nginx"
      annotations: {
        "fortiweb-login" : "fwb-login1",
        "fortiweb-ctrl-log" : "disable",
        "virtual-server-ip" : "192.23.133.6",
        "virtual-server-addr-type" : "ipv4",
        "virtual-server-interface" : "port2",
        "server-policy-web-protection-profile" : "Inline Standard Protection",
        "server-policy-https-service" : "HTTPS",
        "server-policy-http-service" : "HTTP",
        "server-policy-syn-cookie" : "enable",
        "server-policy-http-to-https" : "disable"
      }
      hosts:
        - host: www.bankexample.com
          paths:
            - path: /
              pathType: Prefix
    persistentVolume:
      enabled: true
      size: 100Gi
