---
apiVersion: v1
kind: ServiceAccount
metadata:
    name: fos-serviceaccount
    namespace: fos
imagePullSecrets:
    - name: fosimagepullsecret

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
    name: dvwa-svc-reader
rules:
    - apiGroups: [""]
      resources: ["services"]
      verbs: ["get", "watch", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
    name: dvwa-read-svc
    namespace: dvwa
subjects:
    - kind: ServiceAccount
      name: default
      apiGroup: ""
      namespace: fos
roleRef:
    kind: ClusterRole
    name: dvwa-svc-reader
    apiGroup: ""

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
    name: fos-configmap-reader
rules:
    - apiGroups: [""]
      resources: ["configmaps", "services"]
      verbs: ["get", "watch", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
    name: fos-read-configmaps
    namespace: fos
subjects:
    - kind: ServiceAccount
      name: default
      apiGroup: ""
roleRef:
    kind: ClusterRole
    name: fos-configmap-reader
    apiGroup: ""

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
    name: secrets-reader
rules:
    - apiGroups: [""]
      resources: ["secrets"]
      verbs: ["get", "watch", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
    name: read-secrets
    namespace: fos
subjects:
    - kind: ServiceAccount
      name: default
      apiGroup: ""
roleRef:
    kind: ClusterRole
    name: secrets-reader
    apiGroup: ""
