apiVersion: v1
kind: ConfigMap
metadata:
  name: fosconfigpolicy
  namespace: fos
  labels:
      app: fos
      category: config
data:
  type: partial
  config: |-
    config firewall policy
        edit 1
            set name "dvwa"
            set srcintf "eth0"
            set dstintf "eth0"
            set srcaddr "all"
            set dstaddr "dvwa-vip"
            set service "ALL"
            set nat enable
            set action accept
        next
    end
