---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fos
  namespace: fos
  labels:
    app: fos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fos
  template:
    metadata:
      annotations:
        container.apparmor.security.beta.kubernetes.io/fos: unconfined
      labels:
        app: fos
        api: allow
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
        - name: fos
          image: ghcr.io/robinmordasiewicz/fos:latest
          ports:
            - containerPort: 80
              name: fos
            - name: isakmp
              containerPort: 500
              protocol: UDP
            - name: ipsec-nat-t
              containerPort: 4500
              protocol: UDP
          volumeMounts:
            - mountPath: /data
              name: data-volume
          env:
            - name: fos-license
              valueFrom:
                configMapKeyRef:
                  name: fos-license
                  key: license
          securityContext:
            allowPrivilegeEscalation: true
            capabilities:
              add: ["NET_ADMIN", "SYS_ADMIN", "NET_RAW"]
          resources:
            requests:
              cpu: 4m
              memory: 2Gi
            limits:
              cpu: 8000m
              memory: 4096Mi
        - name: devcontainer
          securityContext:
            allowPrivilegeEscalation: true
            runAsUser: 1000
            runAsGroup: 1000
          command:
            - "sleep"
            - "604800"
          stdin: true
          tty: true
          image: ghcr.io/robinmordasiewicz/devcontainer@sha256:01962cc8185dea71c4d46151542c56b00ef45c6f198a54e772a35249fa6ed97c
          workingDir: /home/vscode
          volumeMounts:
            - name: data-volume
              mountPath: /data
            - name: sidecar-volume
              mountPath: /opt/bin
          resources:
            requests:
              cpu: 1m
              memory: 200Mi
            limits:
              cpu: 1000m
              memory: 512Mi
      volumes:
        - name: data-volume
          emptyDir: {}
        - name: sidecar-volume
          configMap:
            name: sidecar
            defaultMode: 0755
---
apiVersion: v1
kind: Service
metadata:
  name: fos
  namespace: fos
spec:
  ports:
    - port: 8001
      targetPort: 8001
  selector:
    app: fos
  type: ClusterIP
