---
apiVersion: v1
kind: ServiceAccount
metadata:
    name: fos-serviceaccount
    namespace: fos
imagePullSecrets:
    - name: fosimagepullsecret

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
    name: fos-configmap-reader
rules:
    - apiGroups: [""]
      resources: ["configmaps"]
      verbs: ["get", "watch", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
    name: fos-read-configmaps
    namespace: fos
subjects:
    - kind: ServiceAccount
      name: default
      apiGroup: ""
roleRef:
    kind: ClusterRole
    name: fos-configmap-reader
    apiGroup: ""

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
    name: secrets-reader
rules:
    - apiGroups: [""]
      resources: ["secrets"]
      verbs: ["get", "watch", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
    name: read-secrets
    namespace: fos
subjects:
    - kind: ServiceAccount
      name: default
      apiGroup: ""
roleRef:
    kind: ClusterRole
    name: secrets-reader
    apiGroup: ""

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: configmap-manager
  namespace: fos
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["create", "get", "list", "watch", "update", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: configmap-manager-binding
  namespace: fos
subjects:
  - kind: ServiceAccount
    name: default
    namespace: fos
roleRef:
  kind: Role
  name: configmap-manager
  apiGroup: rbac.authorization.k8s.io