apiVersion: v1
kind: ConfigMap
metadata:

metadata:
  name: sidecar
  namespace: fos
  labels:
    app: fos
    category: sidecar
data:
  sidecar.sh: |
    #!/bin/bash
    IPADDRESS=$(kubectl -n dvwa get svc dvwa -o json | jq -r ".spec.clusterIP")
    JSONDATA=$(kubectl -n fos get configmaps fosconfigvip-template -o json | jq '{data,apiVersion,kind}')
    YAMLDATA=$(echo $JSONDATA | yq -P | sed -e s/VAR_DVWA_CLUSTER_IP/${IPADDRESS}/g)
    cat <<EOF > manifest.yaml
    ---
    metadata:
      labels:
        app: fos
        category: config
      name: dvwa-vip
      namespace: fos
    $YAMLDATA
    EOF
    kubectl apply -f manifest.yaml
