---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nvidia-smi
  namespace: nvidia-smi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nvidia-smi
  template:
    metadata:
      labels:
        app: nvidia-smi
    spec:
      nodeSelector:
        "nvidia.com/gpu": "true"
      containers:
        - name: nvidia-smi
          image: nvidia/cuda:11.0.3-runtime-ubuntu20.04
          command: ["/bin/bash", "-c", "--"]
          args: ["while true; do sleep 600; done;"]
          resources:
            limits:
              nvidia.com/gpu: 0
